project:
  type: website

website:
  title: "AIML4OS Landing page"
  navbar:
    left:
      - href: index.qmd
        text: AIML4OS landing page
  page-footer: "aiml4os"

format:
  html:
    theme: cosmo
    toc: true
